# Generated by Django 3.1.7 on 2021-04-13 14:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210402_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='hex_code',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
