# Generated by Django 3.1.7 on 2021-04-13 15:42

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210413_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour',
            old_name='rgb_code',
            new_name='rgb_colour',
        ),
        migrations.AddField(
            model_name='colour',
            name='rgb_background',
            field=colorful.fields.RGBColorField(default='0,0,0'),
        ),
        migrations.AddField(
            model_name='colour',
            name='rgb_border',
            field=colorful.fields.RGBColorField(default='0,0,0'),
        ),
    ]
