# Generated by Django 3.1.7 on 2021-05-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210414_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
