# Generated by Django 3.1.7 on 2021-05-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210508_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='friendly_name',
            field=models.CharField(default='Colour', max_length=254),
        ),
        migrations.AlterField(
            model_name='range',
            name='friendly_name',
            field=models.CharField(default='Range', max_length=254),
        ),
        migrations.AlterField(
            model_name='style',
            name='friendly_name',
            field=models.CharField(default='Style', max_length=254),
        ),
    ]
